app:
  build: ./Cabot
  links:
    - db
    - celery_broker
    - smtp
  volumes:
    - /cabot
  env_file: cabot_env

db:
  image: postgres
  volumes:
    - /var/lib/cabotdb:/var/lib/postgresql
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker

celery_broker:
  image: redis

smtp:
  image: tianon/exim4

nginx:
  image: nginx
  ports:
     - "8080:8080"
  links:
     - app
  volumes_from:
     - app
  volumes:
     - ./Cabot/nginx.conf:/etc/nginx/nginx.conf:ro
